import { useState, useRef, useEffect } from "react";
import { Download, ChevronDown, FileJson, FileText, Code2, Terminal } from "lucide-react";
import type { ExtractResponse } from "../types";

interface Props {
  data: ExtractResponse;
}

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function toCSV(data: ExtractResponse): string {
  const header = ["Element Name", "Type", "Mode", "Tag", "Strategy", "Locator Value", "Score"];
  const rows = data.elements.map((el) => [
    `"${el.element_name}"`,
    el.element_type,
    el.mode,
    el.tag,
    el.recommended_locator.strategy,
    `"${el.recommended_locator.value}"`,
    el.recommended_locator.score,
  ]);
  return [header.join(","), ...rows.map((r) => r.join(","))].join("\n");
}

function toPlaywright(data: ExtractResponse): string {
  const lines = [
    `// Generated by UI Extractor — ${data.page_name}`,
    `// Playwright (TypeScript) locators`,
    ``,
    `import { Page } from '@playwright/test';`,
    ``,
    `export const locators = (page: Page) => ({`,
  ];
  for (const el of data.elements) {
    const name = el.element_name.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase();
    const { strategy, value } = el.recommended_locator;
    const pw = strategy.includes("id")
      ? `page.locator('${value}')`
      : strategy.includes("xpath")
      ? `page.locator('xpath=${value}')`
      : `page.locator('${value}')`;
    lines.push(`  ${name}: ${pw},  // score: ${el.recommended_locator.score}`);
  }
  lines.push(`});`);
  return lines.join("\n");
}

function toSelenium(data: ExtractResponse): string {
  const lines = [
    `# Generated by UI Extractor — ${data.page_name}`,
    `# Selenium (Python) locators`,
    ``,
    `from selenium.webdriver.common.by import By`,
    ``,
    `class Locators:`,
  ];
  for (const el of data.elements) {
    const name = el.element_name.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase();
    const { strategy, value } = el.recommended_locator;
    const by = strategy.includes("xpath")
      ? `By.XPATH, "${value}"`
      : `By.CSS_SELECTOR, "${value}"`;
    lines.push(`    ${name} = (${by})  # score: ${el.recommended_locator.score}`);
  }
  return lines.join("\n");
}

const menuItems = [
  {
    icon: FileJson,
    label: "Export JSON",
    desc: "Full extraction result",
    action: (data: ExtractResponse) => {
      downloadBlob(JSON.stringify(data, null, 2), `${data.page_name}.json`, "application/json");
    },
  },
  {
    icon: FileText,
    label: "Export CSV",
    desc: "Spreadsheet-friendly",
    action: (data: ExtractResponse) => {
      downloadBlob(toCSV(data), `${data.page_name}.csv`, "text/csv");
    },
  },
  {
    icon: Code2,
    label: "Export Playwright",
    desc: "TypeScript locators",
    action: (data: ExtractResponse) => {
      downloadBlob(toPlaywright(data), `${data.page_name}.locators.ts`, "text/plain");
    },
  },
  {
    icon: Terminal,
    label: "Export Selenium",
    desc: "Python locators",
    action: (data: ExtractResponse) => {
      downloadBlob(toSelenium(data), `${data.page_name}.locators.py`, "text/plain");
    },
  },
];

export function ExportMenu({ data }: Props) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const h = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", h);
    return () => document.removeEventListener("mousedown", h);
  }, []);

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-2 px-4 py-2 rounded-xl border border-accent/30 bg-accent/10 text-accent hover:bg-accent/20 hover:border-accent/50 transition-all text-sm font-medium"
      >
        <Download size={15} />
        Export
        <ChevronDown size={13} className={`transition-transform ${open ? "rotate-180" : ""}`} />
      </button>

      {open && (
        <div className="absolute top-full right-0 mt-1.5 z-30 w-56 rounded-2xl border border-bg-border bg-bg-elevated shadow-2xl shadow-black/60 overflow-hidden animate-fade-in">
          <div className="p-1.5">
            {menuItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.label}
                  onClick={() => { item.action(data); setOpen(false); }}
                  className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl hover:bg-bg-hover transition-colors text-left group"
                >
                  <div className="w-8 h-8 rounded-lg bg-bg-surface flex items-center justify-center flex-shrink-0 group-hover:bg-accent/10 transition-colors">
                    <Icon size={15} className="text-slate-400 group-hover:text-accent transition-colors" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-slate-200">{item.label}</p>
                    <p className="text-xs text-slate-500">{item.desc}</p>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
